name: samh_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  mocktail: ^1.0.4

  cupertino_icons: ^1.0.8
  easix: ^1.1.0
  talker_riverpod_logger: ^4.4.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1
  intl: any
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  flutter_form_builder: ^9.4.1
  form_builder_validators: ^11.0.0
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  go_router_builder: ^2.7.1
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  riverpod_test: ^0.1.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
